### ISSUE TITLE
Carousel Doest Scroll Automatically

### ISSUE THREAD

**Issue by Allansmx1** [crpozo/extended-carousel-bs5#1]
Hi! Good Day Sir, I'm a beginner in using bootstrap 5, thank you very much for your extended carousel, Ive been able to use it on my project looks nice, but the multiple columns carousel doesnt scroll automatically, i added interval but it only scrolls on click i have no knowledge in javascript so i cant undestand your code, can you help me out how to get it working, advance thanks to you

**Comment by crpozo** [comment]
Hi, thank you for the support. I have uploaded a new version so you can have a better view of the demo page. Regarding you query just add data-bs-ride="carousel" to active the carousel on load.

**Comment by Allansmx1** [comment]
Thank you very much thumbs up to you sir
